name: Greetings

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submitting your first issue!"
        pr-message: "Thank you for submitting your first pull request!"
